CREATE TABLE Turnero.Pacientes (Id_pte INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
Apellido_pte VARCHAR (50) NOT NULL,
Nombre_pte VARCHAR (59) NOT NULL,
DNI_pte VARCHAR (10) NOT NULL,
OS_pte VARCHAR (60) NOT NULL,
Tel_pte VARCHAR (15) NOT NULL,
Cardiopata BOOLEAN NOT NULL) ENGINE = InnoDB;